Update README.md
smallcloudai/.github pull request #1
Opened 2024-10-30 05:44 UTC by avie66

Added more description about Refact and Community

2024-12-06 11:34 UTC, hazratisulton requested changes

2024-12-06 11:34 UTC, hazratisulton commented on profile/README.md
> +Refact is a powerful AI coding assistant that combines completion, refactoring, chat, and more. Get work done faster with context-aware code completion, integrated in-IDE chat, and a powerful Toolbox
Do we want to mention the toolbox?

2024-12-11 05:24 UTC, avie66 commented on profile/README.md
> +Refact is a powerful AI coding assistant that combines completion, refactoring, chat, and more. Get work done faster with context-aware code completion, integrated in-IDE chat, and a powerful Toolbox
We can ignore about toolbox

2024-12-11 05:26 UTC, avie66 reviewed
Removed toolbox

2024-12-13 07:02 UTC, hazratisulton approved these changes

2025-02-27 10:20 UTC, merged